<?php

namespace AppBundle\Repository;

/**
 * MicropostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MicropostRepository extends \Doctrine\ORM\EntityRepository
{
}
