imports:
    - { resource: config.yml }

doctrine:
    dbal:
        url: "%env(DATABASE_URL)%"
        driver: pdo_pgsql
        charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        metadata_cache_driver: apcu
        result_cache_driver: apcu
        query_cache_driver: apcu

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: 'php://stderr'
            level: debug
        console:
            type: console
