# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
  app.action_listener:
    class: AppBundle\EventListener\RememberListener
    arguments: ['@security.token_storage']
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  amazon_storage:
    class: AppBundle\Services\AmazonS3Service
    arguments:
      - "%kernel.environment%"
      - "%env(S3_BUCKET)%"
      - credentials:
        key:     "%env(S3_ACCESS_KEY)%"
        secret:  "%env(S3_SECRET_KEY)%"
        region:  "%env(S3_REGION)%"
        version: "2006-03-01"