# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  app.action_listener:
    class: AppBundle\EventListener\RememberListener
    arguments: ['@security.token_storage']
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  app.amazon_storage:
    class: AppBundle\Services\AmazonS3Service
    arguments:
      - "%kernel.environment%"
      - "%env(S3_BUCKET)%"
      - s3arguments:
        version: "latest"
        region:  "%env(S3_REGION)%"
        credentials:
          key:     "%env(S3_ACCESS_KEY)%"
          secret:  "%env(S3_SECRET_KEY)%"
